spring.application.name=SpringJDBC

#spring.datasource.url=jdbc:mysql:///springcruddb
spring.datasource.url=jdbc:mysql://localhost:3306/springcruddb
spring.datasource.username=root
spring.datasource.password=@shriram82630

